// src/components/Badge.vue
<script setup lang="ts">
interface Props {
    icon: string
    label: string
}

defineProps<Props>()
</script>

<template>
    <div
        flex="~ row"
        bg="gray-100 hover:gray-200"
        class="p-1 rounded-lg gap-2 w-fit items-center justify-center hover:(cursor-pointer)"
    >
        <i class="size-5" :class="[icon]" /> {{ label }}
    </div>
</template>

// src/components/Badge.tsx
import React from "react"

export interface BadgeProps {
	icon: React.JSX.Element
	text: string
	url: string
}

export default function Badge({ icon, text, url }: BadgeProps) {
	return (
		<a href={url} target='_blank'>
			<div className='flex items-center justify-center gap-1 bg-stone-900 py-1 px-2 rounded-md w-min hover:(bg-stone-800 cursor-pointer) duration-300'>
				{icon}
				<p className='text-gray-300 text-nowrap'>{text}</p>
			</div>
		</a>
	)
}
